-- =========================================================
-- Database: maps_db
-- Cleaned PostgreSQL init script
-- =========================================================

-- Connect to the database created by Docker
\connect maps_db

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

-- =========================================================
-- Tables
-- =========================================================

CREATE TABLE public.maps (
    map_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    map_name varchar(128) NOT NULL,
    map_min_zoom integer NOT NULL,
    map_max_zoom integer NOT NULL,
    map_tiles_link text NOT NULL,
    map_description text,
    map_img text
);

CREATE TABLE public.overlays (
    overlay_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    overlay_name varchar(128) NOT NULL
);

CREATE TABLE public.map_icons (
    icon_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon_name varchar NOT NULL,
    icon_link varchar NOT NULL
);

CREATE TABLE public.map_overlays (
    map_id integer NOT NULL,
    overlay_id integer NOT NULL,
    PRIMARY KEY (map_id, overlay_id),
    FOREIGN KEY (map_id) REFERENCES public.maps(map_id) ON DELETE CASCADE,
    FOREIGN KEY (overlay_id) REFERENCES public.overlays(overlay_id) ON DELETE CASCADE
);

CREATE TABLE public.markers (
    marker_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    marker_name varchar(128) NOT NULL,
    marker_lat real NOT NULL,
    marker_lng real NOT NULL,
    marker_desc text,
    marker_img text,
    icon_id integer,
    map_id integer NOT NULL,
    overlay_id integer NOT NULL,
    FOREIGN KEY (map_id) REFERENCES public.maps(map_id) ON DELETE CASCADE,
    FOREIGN KEY (overlay_id) REFERENCES public.overlays(overlay_id) ON DELETE CASCADE,
    CONSTRAINT markers_icons
        FOREIGN KEY (icon_id)
        REFERENCES public.map_icons(icon_id)
        NOT VALID
);

-- =========================================================
-- Data
-- =========================================================

COPY public.map_icons (icon_id, icon_name, icon_link) FROM stdin;
1	bridge-icon	http://127.0.0.1:8884/icons/bridge-icon.svg
2	castle-icon	http://127.0.0.1:8884/icons/castle-icon.svg
3	cave-icon	http://127.0.0.1:8884/icons/cave-icon.svg
4	dead-eye-icon	http://127.0.0.1:8884/icons/dead-eye-icon.svg
5	dungeon-icon	http://127.0.0.1:8884/icons/dungeon-icon.svg
6	forest-camp-icon	http://127.0.0.1:8884/icons/forest-camp-icon.svg
7	forest-icon	http://127.0.0.1:8884/icons/forest-icon.svg
8	meadows-icon	http://127.0.0.1:8884/icons/meadows-icon.svg
9	mines-icon	http://127.0.0.1:8884/icons/mines-icon.svg
10	monsters-icon	http://127.0.0.1:8884/icons/monsters-icon.svg
11	mountain-road-icon	http://127.0.0.1:8884/icons/mountain-road-icon.svg
12	mountains-icon	http://127.0.0.1:8884/icons/mountains-icon.svg
13	religion-icon	http://127.0.0.1:8884/icons/religion-icon.svg
14	ruins-icon	http://127.0.0.1:8884/icons/ruins-icon.svg
15	tavern-icon	http://127.0.0.1:8884/icons/tavern-icon.svg
16	town-icon	http://127.0.0.1:8884/icons/town-icon.svg
17	village-icon	http://127.0.0.1:8884/icons/village-icon.svg
18	default-icon	http://127.0.0.1:8884/icons/default-icon.svg
\.

COPY public.overlays (overlay_id, overlay_name) FROM stdin;
1	Cities
2	Villages
3	Woodlans
4	Castles
5	Ruins
6	Interesting places
7	Mountains
8	Mines
9	Dungeons
10	Taverns
\.

COPY public.maps (map_id, map_name, map_min_zoom, map_max_zoom, map_tiles_link, map_description, map_img) FROM stdin;
1	Merges	2	4	http://127.0.0.1:8884/maps/Merges/{z}/{y}/{x}.webp	# Merges: The Valley of Whispering Winds\n## A Geography of Shadow and Stone\n\nWelcome to the **Merges**, a basin of treacherous beauty caught between the crushing weight of the **Whistling Peaks** and the silent expanse of the western forests. It is a land where the wind never truly stops blowing, and **silence is suspicious**.\n\n### The Lay of the Land\n---\n\nThe valley is not merely a passage; it is a trap for the unwary. The roads are well-worn, suggesting trade, but the overgrown ruins suggest that civilization here is a ~~permanent state~~ **fleeting privilege**. The geography is defined by water that flows deceptively calm and woods that seem to lean in as you pass.\n\n> "They call it 'Merges' because here the wind merges with the soul."\n>> ...is what the poets claim in the taverns of Nestal...\n> > > ...but the soldiers know it's where the living merge with the dead.\n\n### Key Locations\n\nBased on the cartographer's survey, these are the primary points of interest (and danger):\n\n+ **The Citadels of Men**\n  - **Nestal**\n    The largest stronghold, sitting comfortably near the southern forests. Its red roofs hide a nobility that has grown paranoid of the woods.\n  - **Tarantez**\n    A fortified outpost in the west. It guards the river, but its walls face *inward* toward the town, not just outward.\n  - **Istenis**\n    Hidden in the shadow of the mountains. The sun reaches Istenis only for a few hours a day.\n\n+ **The Wilds**\n  - **Raven Woods**\n    A massive, sprawling thicket. The trees are dense, and the canopy chokes out the light.\n  - **Deceptive Wetlands**\n    Located in the northwest. The ground here looks solid, but it is a lie.\n    - Home to the ruins of **Mothar**.\n  - **Whistling Peaks**\n    The jagged mountain range to the east that creates the valley's unnatural wind currents.\n\n### Rules of the Road\n\n1. Stick to the main roads between **Nestal** and **Istenis**.\n2. If you see lights in the **Deceptive Wetlands**, do not follow them.\n3. Keep your weapons oiled; the dampness here rusts steel and rots bowstrings.\n\n---\n\n## Recovered Patrol Log\n\nA waterlogged journal found near the bridge crossing into the Windy Valley. The ink is running:\n***Day 4: We lost Kaelen near Mothar. Day 5: He stepped off the path. Just one step. Day 6: The mud didn't sink. It grabbed him. NOTE: DO NOT STOP FOR THE WOUNDED.\nScratched into the leather cover is the code: `0-4-0-4`.***\n\n\n---\n\n## Regional Threat Assessment\n\nA quick reference for travelers traversing the Merges:\n\n| Location | Primary Threat | Survival Chance |\n| :------- | :------------- | --------------: |\n| **Whistling Peaks** | Harpies, Rock Slides | Moderate |\n| **Raven Woods** | Giant Arachnids, Bandits | Low |\n| **Deceptive Wetlands** | Drowning, Will-o'-the-wisps | **Very Low** |\n| **Town of Nestal** | Corrupt Guards, Thieves | High |\n\n---\n\n*Keep your eyes on the horizon, traveler. In the Merges, the landscape changes when you blink.*	https://images.alphacoders.com/900/thumb-1920-900186.jpg
\.

COPY public.map_overlays (map_id, overlay_id) FROM stdin;
1	1
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
1	10
\.

COPY public.markers (marker_id, marker_name, marker_lat, marker_lng, marker_desc, marker_img, icon_id, map_id, overlay_id) FROM stdin;
1	Nestal	-35.9	27.82	### Nestal, The Divided City\n\nNestal is the strategic throat of the Merges, a massive city built astride the great river that flows into the valley from the south. It is a city physically and socially bisected by the rushing waters, a stark monument to inequality.\n\n**The East Bank (The Gilded Side):** This is the home of old money, merchant princes, and the nobility. It boasts paved streets, stone mansions with red-tiled roofs, and magical streetlamps that burn all night. It is clean, orderly, and heavily patrolled by the well-paid City Watch.\n\n**The West Bank (The Silt Side):** Connected by bridges, this is where the raw goods from the south are offloaded. It is a chaotic sprawl of muddy docks, leaning wooden tenements, warehouses, and smoky taverns. It is ruled by dock gangs and crime syndicates, where life is cheap and the City Watch rarely ventures after dark.\n\nConnecting the two halves is the massive, fortified "Bridge of Tithes." Here, the city's corrupt bureaucracy sits, extracting heavy taxes on every single item that crosses the river in either direction. Nestal is the center of commerce and corruption, a place where incredible wealth flows just yards away from abject poverty.	\N	2	1	4
2	Tarantez	-33.86	-75.84	### Tarantez, The Gilded Cage\n\nTarantez rises from the western meadows like an island in a golden sea. It remains the undisputed breadbasket of the Merges, its vast silos overflowing with grain that feeds half the valley. On the surface, it is a picture of pastoral idyllic life: warm, sunny days, bustling markets, and the smell of baking bread permeating the air.\n\nHowever, the facade begins to crack if one looks closely. The city walls are suspiciously tall and thick for a simple agricultural hub, built more like a fortress than a trading post. The city gates are barred tight at the exact moment of sunset—no exceptions. The magnificent fields, so beautiful by day, are strictly forbidden territory after dark.\n\nThere are persistent rumors in the valley about Tarantez. Rumors of things that slither through the tall wheat under the light of the moon, "scarecrows" that move when you aren't looking, and the dark bargains the Grain Barons have struck to ensure the harvest never fails, regardless of droughts or blights. Tarantez is a city of full bellies and fearful eyes, a gilded cage where safety is bought with absolute obedience to the curfew.\n\n#### The Two Faces of Tarantez\n\n| Feature | Day (The Golden Hours) | Night (The Barred Hours) |\n| :--- | :--- | :--- |\n| **Atmosphere** | Bustling, warm, inviting. | Silent, tense, paranoid. |\n| **The Fields** | Filled with workers and song. | Empty. Lethal territory. |\n| **The Guards** | Helpful city watchmen. | Heavily armed mercenaries on the walls, facing *out*. |	\N	16	1	1
3	Verdin	22.07	-12.45	### Verdin, The Crossroads\n\nVerdin is the transient heart of the Merges, sitting squarely where the great northern trade route intersects with the east-west road between Tarantez and Nestal. It is a bustling, chaotic, mud-splattered hub that exists solely to cater to people who are just passing through.\n\nThe village is a collection of stables, supply stores, and wagon repair shops, but its soul is the legendary "Crossroads Inn." This massive, sprawling timber building is always expanding. Its central hearth fire has reportedly not been allowed to die out in over fifty years, a symbol of eternal hospitality.\n\nVerdin is where the valley's information converges. Spies, merchants, sellswords, and thieves rub shoulders in the crowded taprooms. It is the best place in the Merges to find work, hire a guide, or hear the latest rumors—though separating truth from drunken fiction is a skill in itself. It's a place where you can find anything you need, provided you keep one hand on your coin purse and the other near your dagger.\n\n#### Services Available in Verdin\n\n| Service | Quality | Cost | Notes |\n| :--- | :--- | :--- | :--- |\n| **Stabling** | Excellent | High | Your horse will eat better than you do. |\n| **Lodging (Common)** | Poor | Low | Crowded common rooms, expect fleas and loud snoring. |\n| **Lodging (Private)** | Good | Exorbitant | Clean sheets are a luxury here. |\n| **Information** | Varies | A drink | Most rumors are lies; the expensive ones are usually true. |	\N	15	1	10
4	Bridge of the dead horse	27.27	33.29	### The Bridge of the Dead Horse\n\nSpanning a treacherous, fast-flowing tributary river on the road to Istenis is a sturdy, unremarkable stone bridge. It would be just another piece of infrastructure if not for the grim legend attached to it—a legend that is frighteningly recent.\n\nOnly three years ago, a wealthy merchant was crossing the bridge with his prize stallion. In the dead center of the span, the horse simply stopped. It did not rear or bolt; it planted its hooves, stared intently at the empty air on the far bank, and began to tremble violently. No amount of coaxing, pulling, or whipping could move the beast an inch forward or backward. It stood paralyzed by an unseen terror for two hours until its heart simply gave out from the strain, and it collapsed dead on the stones.\n\nThe merchant, spooked beyond reason, fled and left the valuable animal where it fell. The bones are gone now, but a palpable aura of intense, irrational dread still washes over anyone crossing the bridge alone, especially at twilight. Travelers have taken to leaving small offerings—an apple, a copper coin—at the center of the bridge to appease whatever invisible horror the horse saw, praying it remains invisible.	\N	1	1	6
5	Old Hector Mines	20.22	67.6	### Old Hector Mines\n\nBefore the Silverstone strike, the Hector Mines were the primary source of mineral wealth in the foothills. Thirty years ago, they were abruptly abandoned following a catastrophic collapse that swallowed an entire night shift of two hundred workers and opened a fissure into something *else*.\n\nToday, the Old Hector Mines are a festering wound in the earth, shunned by locals. The wooden supports at the entrances are rotted and covered in strange, luminescent fungi. The lower tunnels are flooded with toxic, sulfuric water. Despite the rusted warning signs posted by the regional authorities, the mines lure in foolish adventurers and desperate treasure hunters with rumors of veins of gold left untouched during the evacuation.\n\nVery few who enter return. Those who do speak of strange, chitinous clicking sounds echoing from the deep shafts, tracks of creatures that do not belong in the surface world, and a pervasive feeling of ancient hunger that emanates from the dark. It is a classic dungeon, where the darkness itself seems to be waiting for a meal.\n\n> **Posted Sign (Rusted Iron):**\n> "DANGER. MINE UNSTABLE. GAS POCKETS AND STRUCTURAL FAILURE IMMINENT. BY ORDER OF THE Jarl: DO NOT ENTER. (Scratched underneath: *They are still down there. I heard them screaming.*)"	\N	5	1	9
6	The Silverstone Mines	5.44	68.03	### The Silverstone Mines\n\nA relatively new addition to the region's geography, the Silverstone Mines have transformed a quiet stretch of foothills into a chaotic hive of industry and greed. The discovery of an unusually pure, massive vein of silver five years ago triggered a "silver rush" that drew laborers, fortune-seekers, and opportunists from across the lands.\n\nThe area is now a sprawling boomtown of canvas tents and hastily erected wooden shacks. The air is permanently thick with gray rock dust, and the rhythmic clang of pickaxes and mining machinery rings out day and night without cease. The silver has brought immense wealth to the mine owners, but it has also brought violence, gambling, and a brutal dog-eat-dog culture among the miners.\n\nThe area is patrolled by the "Silver Shields," highly paid private mercenaries who protect the ore shipments with lethal force. The miners themselves have a hollow, exhausted look, their skin stained gray by the dust, working dangerous shifts in the cramping dark for a mere sliver of the profits.	\N	9	1	8
7	The Spruce Village	-30.93	8.68	### The Spruce Village\n\nNestled near the northern tree line where the mountains meet the forests, Spruce Village is a quiet, industrious settlement that smells perpetually of fresh sawdust, pine resin, and woodsmoke. It is a community dedicated entirely to the craft of woodworking.\n\nThe villagers here are master carpenters, joiners, and carvers whose skills are renowned throughout the entire continent. They do not merely cut wood; they claim to "listen" to it. They practice sustainable forestry, singing to the trees before felling them and replanting two for every one taken. This respect seems to imbue their creations with a subtle, almost magical quality.\n\nFurniture built in Spruce Village is known for uncanny durability and a faint, pleasant scent that never fades, even after a century. It is said that a chair from Spruce Village will adjust itself slightly to the sitter, making it unnervingly comfortable. The village is peaceful and orderly, but the inhabitants are fiercely protective of their groves and their craft secrets.\n\n> **Merchant's Saying:**\n> "You buy a Tarantez table to eat on. You buy a Spruce Village table to pass down to your grandchildren's grandchildren."	\N	17	1	2
8	The Forest Enclave	-13.28	-19.16	### The Forest Enclave\n\nDeep inside the Raven Woods, hidden by natural barriers of woven briars and subtle misdirection magic, lies the Forest Enclave. This is not a village in the human sense; it is a settlement grown *from* the forest rather than built *in* it.\n\nDwellings are formed from massive, hollowed-out trees or shaped from living branches woven together. The only light at night comes from carefully cultivated bioluminescent fungi and mosses that glow with soft blues and greens. This is the sanctuary of the Circle of the Raven—druids, rangers, and others who have sworn to protect the wild.\n\nThey live in an uneasy truce with the surrounding dangers, protected by ancient pacts with the forest spirits. They are secretive and highly distrustful of outsiders, especially those bearing axes or the smell of industry. However, they are known to offer sanctuary and powerful natural healing to those who show genuine respect for the wild. In the Enclave, the line between plant, animal, and person is blurred.	\N	13	1	2
9	Moonshine Lake	-23.87	-26.87	### Moonshine Lake\n\nHidden deep within the uncharted heart of the Raven Woods, protected by a maze of shifting thorns, lies Moonshine Lake. It is a perfectly circular body of water, uncannily still. Even when the winds howl through the treetops above, the surface of the lake remains as smooth as polished glass.\n\nThe defining characteristic of the lake is its reflection. No matter the time of day, the weather, or the actual phase of the moon in the sky, the lake's surface always reflects a perfect, gigantic full moon. This impossible reflection casts a soft, cold, silvery luminescence that lights the surrounding banks.\n\nIt is a place of staggering, almost painful beauty, but also subtle, insidious danger. Gazing into the reflective surface for too long is said to entrap the mind. The viewer no longer sees their own face, but manifestations of their deepest desires or paralyzing fears, illusions so convincing they have lured many travelers to step into the freezing, bottomless depths.\n\n> **Druidic Warning Marker (Translated):**\n> "Here lies the mirror of the soul. Drink not its waters, for they are starlight liquified. Look not its depths, for they show only what you lack. Turn back."	\N	18	1	6
10	The Raven Woods	-44.34	-29.36	### The Raven Woods\n\nThe Raven Woods is not merely a forest; it is a primal, sprawling entity that dominates the southern landscape, believed by elves and druids to be older than the mountains themselves. It is a remnant of a wilder, darker age before humanity carved its roads into the valley.\n\nEntering the Raven Woods feels like stepping into another realm. The canopy of immense, ancient trees—some wider than a farmhouse—is so dense that the forest floor exists in perpetual, cool twilight. The flora here is oversized and vibrant in dark hues of violet, deep crimson, and emerald green. Time itself seems to warp and pool inside the treeline; a few hours spent wandering its mossy paths can translate to days having passed in the outside world.\n\nThe forest is not inherently "evil" in the way a demon is, but it is profoundly indifferent to mortal life. It has its own ancient rules, its own terrifying ecosystem of apex predators, and a deep, brooding intelligence that feels like it is watching every step an intruder takes.\n\n**The First Rule of the Woods:**\n*Do not bring fire. The woods remember fire, and they will snuff it out—along with the one holding it.*	\N	7	1	3
11	Deceptive Wetlands	47.87	-63.98	### The Deceptive Wetlands\n\nSurrounding the sunken ruins of Mythar is a vast, treacherous expanse that has claimed more lives than any war in the Merges. The Deceptive Wetlands earned their name through centuries of vanished travelers and swallowed caravans. It is a landscape that actively lies to the senses.\n\nWhat appears to be a solid path of vibrant green moss is often a paper-thin crust floating over a sinkhole of grasping, anaerobic mud. Trees that look sturdy are rotted hollow, waiting for a hand to grab them for support before collapsing. Strange, colorless flowers bloom on the few true islands, releasing a faint, sweet pollen that subtly warps depth perception and clouds judgment, making bad ideas seem brilliant.\n\nThe greatest danger, however, arrives with twilight. The "Bog Lanterns"—pale, bobbing wisps of magical light—hover over the deepest, deadliest parts of the swamp. To an exhausted traveler, they look invitingly like the warm lamps of a distant inn or a safe harbor, leading the unwary off the few safe paths and into a watery grave. To reach Mythar, one must navigate this gauntlet of illusions, where the land itself seems to conspire against intrusion.\n\n> **Recovered Journal Entry, Waterstained:**\n> "Day 3 in the muck. We saw lights to the east. Captain says it's Mythar. The guide says it's a trap. The guide is terrified. I think I trust the guide more, but I am so very cold, and the lights look so warm..."	\N	8	1	3
12	The Creaking Forest	33.28	-36.39	### The Creaking Forest\n\nBefore one even reaches the dangers of the Wetlands, they must traverse the Creaking Forest. This woodland is the only viable land route to Mythar from the east, and it is a psychological ordeal. It is a forest of ancient, brittle trees with bark the color of ash and leaves that seem permanently wilted.\n\nThe forest gets its name from the sound. It is never silent here. As the wind from the distant mountains filters through the tightly packed, twisted trunks, the wood rubs against wood in a ceaseless, mournful chorus. It sounds like the groaning of ship rigging in a storm, amplified a thousand times—a cacophony of sighs, shrieks, and cracking timber that can mask the approach of predators or slowly drive a traveler to the edge of panic.\n\nLocals whisper that the forest is semi-sentient, a labyrinth that subtly shifts its paths when you aren't looking, turning travelers around until they are hopelessly lost in the gray gloom, doomed to add their bones to the gnarled roots.\n\n#### Sensory Hazards\n\n* **Sound:** The constant grinding noise makes sleep difficult and stealth impossible.\n* **Sight:** The canopy is so dense it blocks 90% of sunlight, creating perpetual twilight. The gray-on-gray palette makes navigation difficult.\n* **Touch:** The bark is jagged and sharp; the underbrush is thorny and grabs at clothing like desperate hands.	\N	10	1	3
15	Istenis	42.55	62.58	### Istenis, The Anvil\n\nIstenis is the imposing fortress-city of the dwarves, not built upon the mountain, but carved directly into the living rock of the eastern peaks. From the outside, it appears as a sheer cliff face punctuated by arrow slits and massive, fortified gates, with smoke venting constantly from hundreds of chimneys carved into the high stone.\n\nInside, Istenis is a massive, interconnected machine dedicated to industry, fire, and unyielding stone. The heat in the crafting districts is intense, and the air smells of hot metal and coal dust. The rhythmic, thundering sound of thousands of hammers hitting anvils is the city's eternal heartbeat, audible for miles.\n\nThe dwarves of Istenis are stoic, isolationist, and masterful craftsmen who distrust magic and human politics in equal measure. They produce the finest weapons, armor, and architectural supports in the Merges, trading their peerless steel for the food and textiles they cannot grow on stone. To step into Istenis is to step into a world illuminated by the glow of molten metal and ruled by the strict discipline of the forge.	\N	2	1	4
16	Mythar	40.58	-72.42	### Mythar, The Sunken Ruin\n\n**"We don't live in Mythar. We survive it."**\n-- *Old Man Hemlock, scavenger of the Second Tier.*\n\nMythar was once an architectural marvel, a city built in defiance of the wetlands. Now, it is a testament to the earth's patience. The lower half of the city has completely succumbed to the bog, leaving only the upper spires, cathedral roofs, and highest tower floors piercing the murky surface like the skeletal fingers of a drowning giant.\n\nYet, life stubbornly clings to these ruins. A desperate population of scavengers, outcasts, and those with nowhere else to go inhabit the crumbling upper levels. They navigate their precarious world via a chaotic web of rotting rope bridges and creaking wooden walkways suspended above the deadly muck. The air is perpetually thick with the smell of mildew, sulfur, and stagnant water.\n\nLife here revolves around "The Dive"—the dangerous act of descending into the submerged lower districts to retrieve artifacts, waterproof chests, and sealed casks from a wealthier time. It is a city of ghosts, and the loudest sound at night is often the groan of ancient stone foundations finally giving way, sending another section of history sinking into the depths.\n\n#### Survival Protocol in Mythar\n\n| Rule | Reason | Consequence of Failure |\n| :--- | :----- | :--------------------- |\n| **Trust the Rope, Not the Wood** | The bridges are maintained; the old floorboards are rotting from beneath. | A fifty-foot drop into deep sludge. |\n| **Never Dive Alone** | Something needs to pull on the rope if you get stuck... or grabbed. | Becoming a permanent resident of the lower districts. |\n| **Watch the Water Level** | The swamp rises unpredictably after rains in the mountains. | Waking up with swamp water in your lungs. |	\N	14	1	5
\.

-- =========================================================
-- Sequences
-- =========================================================

SELECT setval('public.map_icons_icon_id_seq', 18, true);
SELECT setval('public.maps_map_id_seq', 1, true);
SELECT setval('public.markers_marker_id_seq', 16, true);
SELECT setval('public.overlays_overlay_id_seq', 10, true);
